### ISSUE TITLE
[bmap-tools@3.6] [Built-in case failure] The self-test case fails.

### ISSUE THREAD

**Issue by Tom-python0121** [intel/bmap-tools#81] opened 2021-02-23 03:34 UTC
Hello，I have a problem about the self-test case fails in bmap-tools@3.6.

### Steps to reproduce the issue
```console
[root@centos8 bmap-tools]# python setup.py test
/tmp/root/spack-stage/spack-stage-py-bmap-tools-3.6-6c2mr3mf6rxquyvwbibqd6nhkd54ienc/spack-src/tests/test_api_base.py:200: ResourceWarning: unclosed file <_io.BufferedReader name=10>
  helpers.copy_and_verify_image(compressed, f_copy.name,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ERROR
/home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/python-3.8.5-rvp2d3s6nyt65vfrkkbikqp5pt4wfknj/lib/python3.8/unittest/case.py:704: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/root/spack-stage/spack-stage-py-bmap-tools-3.6-6c2mr3mf6rxquyvwbibqd6nhkd54ienc/spack-src/sparse_6uc40kd7.s9nufu7e.bmap1' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/python-3.8.5-rvp2d3s6nyt65vfrkkbikqp5pt4wfknj/lib/python3.8/subprocess.py:942: ResourceWarning: subprocess 784763 is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/python-3.8.5-rvp2d3s6nyt65vfrkkbikqp5pt4wfknj/lib/python3.8/unittest/case.py:704: ResourceWarning: unclosed file <_io.BufferedReader name=13>
  outcome.errors.clear()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/python-3.8.5-rvp2d3s6nyt65vfrkkbikqp5pt4wfknj/lib/python3.8/unittest/case.py:704: ResourceWarning: unclosed file <_io.BufferedRandom name='/tmp/root/spack-stage/spack-stage-py-bmap-tools-3.6-6c2mr3mf6rxquyvwbibqd6nhkd54ienc/spack-src/sparse_6uc40kd7.i_g7uw3x.copy'>
  outcome.errors.clear()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
test_get_file_system_type (tests.test_bmap_helpers.TestBmapHelpers)
Check a file system type is returned when used with a file ... ok
test_get_file_system_type_no_fstype_found (tests.test_bmap_helpers.TestBmapHelpers)
Check error raised when supplied file doesnt exist ... ok
test_get_file_system_type_symlink (tests.test_bmap_helpers.TestBmapHelpers)
Check a file system type is returned when used with a symlink ... ok
test_is_compatible_file_system_ext4 (tests.test_bmap_helpers.TestBmapHelpers)
Check non-zfs file systems pass compatiblilty checks ...
ok
test_is_compatible_file_system_zfs_invalid (tests.test_bmap_helpers.TestBmapHelpers)
Check compatiblilty check fails when zfs param is set incorrectly ... ok
test_is_compatible_file_system_zfs_valid (tests.test_bmap_helpers.TestBmapHelpers)
Check compatiblilty check passes when zfs param is set correctly ... ok
test_is_zfs_configuration_compatible_disabled (tests.test_bmap_helpers.TestBmapHelpers)
Check compatiblilty check is false when zfs param is set incorrectly ... ok
test_is_zfs_configuration_compatible_enabled (tests.test_bmap_helpers.TestBmapHelpers)
Check compatiblilty check is true when zfs param is set correctly ... ok
test_is_zfs_configuration_compatible_invalid_read_value (tests.test_bmap_helpers.TestBmapHelpers)
Check error raised if any content of zfs config file invalid ... ok
test_is_zfs_configuration_compatible_notinstalled (tests.test_bmap_helpers.TestBmapHelpers)
Check compatiblilty check passes when zfs not installed ... ok
test_is_zfs_configuration_compatible_unreadable_file (tests.test_bmap_helpers.TestBmapHelpers)
Check error raised if any IO errors when checking zfs config file ... FAIL
test (tests.test_compat.TestCompat)
The test entry point. ...
Copied 100%

/home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/python-3.8.5-rvp2d3s6nyt65vfrkkbikqp5pt4wfknj/lib/python3.8/subprocess.py:942: ResourceWarning: subprocess 784772 is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/root/spack-stage/spack-stage-py-bmap-tools-3.6-6c2mr3mf6rxquyvwbibqd6nhkd54ienc/spack-src/tests/test_compat.py:86: ResourceWarning: unclosed file <_io.BufferedReader name=9>
  helpers.copy_and_verify_image(image_path, self._f_copy.name,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
……
======================================================================
ERROR: test (tests.test_api_base.TestCreateCopy)
The test entry point. Executes the '_do_test()' function for files of
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/root/spack-stage/spack-stage-py-bmap-tools-3.6-pslvigjxtct3npd3psf6tckczsrmm2n4/spack-src/tests/test_api_base.py", line 267, in test
    _do_test(f_image.name, image_size, delete=delete)
  File "/tmp/root/spack-stage/spack-stage-py-bmap-tools-3.6-pslvigjxtct3npd3psf6tckczsrmm2n4/spack-src/tests/test_api_base.py", line 200, in _do_test
    helpers.copy_and_verify_image(compressed, f_copy.name,
  File "/tmp/root/spack-stage/spack-stage-py-bmap-tools-3.6-pslvigjxtct3npd3psf6tckczsrmm2n4/spack-src/tests/helpers.py", line 296, in copy_and_verify_image
    writer.copy(bool(random.getrandbits(1)), bool(random.getrandbits(1)))
  File "/tmp/root/spack-stage/spack-stage-py-bmap-tools-3.6-pslvigjxtct3npd3psf6tckczsrmm2n4/spack-src/bmaptools/BmapCopy.py", line 651, in copy
    raise Error("wrote %u blocks from image '%s' to '%s', but should "
bmaptools.BmapCopy.Error: wrote 0 blocks from image '/tmp/root/spack-stage/spack-stage-py-bmap-tools-3.6-pslvigjxtct3npd3psf6tckczsrmm2n4/spack-src/sparse_1peurs4_.9a_ogrqc.zst' to '/tmp/root/spack-stage/spack-stage-py-bmap-tools-3.6-pslvigjxtct3npd3psf6tckczsrmm2n4/spack-src/sparse_1peurs4_.pri4c55_.copy', but should have 526 - bmap file '/tmp/root/spack-stage/spack-stage-py-bmap-tools-3.6-pslvigjxtct3npd3psf6tckczsrmm2n4/spack-src/sparse_1peurs4_.jcqrov2d.bmap1' does not belong to this image

======================================================================
FAIL: test_is_zfs_configuration_compatible_unreadable_file (tests.test_bmap_helpers.TestBmapHelpers)
Check error raised if any IO errors when checking zfs config file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/py-mock-3.0.5-raeh3rzje6pc64xv2bwznbqq7cbv63wz/lib/python3.8/site-packages/mock/mock.py", line 1330, in patched
    return func(*args, **keywargs)
  File "/tmp/root/spack-stage/spack-stage-py-bmap-tools-3.6-pslvigjxtct3npd3psf6tckczsrmm2n4/spack-src/tests/test_bmap_helpers.py", line 105, in test_is_zfs_configuration_compatible_unreadable_file
    BmapHelpers.is_zfs_configuration_compatible()
AssertionError: Error not raised

----------------------------------------------------------------------
Ran 14 tests in 54.381s

FAILED (failures=1, errors=1)
Test failed: <unittest.runner.TextTestResult run=14 errors=1 failures=1>
error: Test failed: <unittest.runner.TextTestResult run=14 errors=1 failures=1>
```
Now I don't know why these two problems came up. Can you help me analyze them?

### Information on your system
* **Python:** 3.8.5
* **Platform:** linux-centos8-aarch64

**Comment by Tom-python0121** [comment] 2021-02-24 02:42
As you can see, here's the error source and the failure source：
```console
[root@centos8 bmap-tools]# ls
1byte_hole_ouj9995j.img.zst      bmaptool             contrib  __main__.py                   rand_hole_1_1cbszam4.img.zst  rand_hole_5_va28mp_n.img.zst  rand_hole_9_p10n26w6.img.zst  sparse_1peurs4_.img.zst
4Khole_f60m19ns.img.zst          bmaptools            COPYING  make_a_release.sh             rand_hole_2_a73tbz60.img.zst  rand_hole_6_g1pg3a3y.img.zst  requirements-test.txt         tests
4Khole_minus_1_nvwp5rpv.img.zst  bmap_tools.egg-info  debian   packaging                     rand_hole_3_etda0s4s.img.zst  rand_hole_7_rpbg5buk.img.zst  setup.cfg                     TODO
4Khole_plus_1_ptl8bbkg.img.zst   build                docs     rand_hole_0_xzaxw5to.img.zst  rand_hole_4_6629dmyu.img.zst  rand_hole_8_urgqh5c1.img.zst  setup.py
[root@centos8 bmap-tools]# vim bmaptools/BmapCopy.py +651
……
    def copy(self, sync=True, verify=True):
        """
        Copy the image to the destination file using bmap. The 'sync' argument
        defines whether the destination file has to be synchronized upon
        return.  The 'verify' argument defines whether the checksum has to be
        verified while copying.
        """

        # Create the queue for block batches and start the reader thread, which
        # will read the image in batches and put the results to '_batch_queue'.
        self._batch_queue = Queue.Queue(self._batch_queue_len)
        thread.start_new_thread(self._get_data, (verify, ))

        blocks_written = 0
        bytes_written = 0
        fsync_last = 0

        self._progress_started = False
        self._progress_index = 0
        self._progress_time = datetime.datetime.now()

        if self.image_size and self._dest_is_regfile:
            # If we already know image size, make sure that destination file
            # has the same size as the image
            try:
                os.ftruncate(self._f_dest.fileno(), self.image_size)
            except OSError as err:
                raise Error("cannot truncate file '%s': %s"
                            % (self._dest_path, err))

        # Read the image in '_batch_blocks' chunks and write them to the
        # destination file
        while True:
            batch = self._batch_queue.get()
            if batch is None:
                # No more data, the image is written
                break
            elif batch[0] == "error":
                # The reader thread encountered an error and passed us the
                # exception.
                exc_info = batch[1]
                reraise(exc_info[0], exc_info[1], exc_info[2])

            (start, end, buf) = batch[1:4]

            assert len(buf) <= (end - start + 1) * self.block_size
            assert len(buf) > (end - start) * self.block_size

            self._f_dest.seek(start * self.block_size)

            # Synchronize the destination file if we reached the watermark
            if self._dest_fsync_watermark:
                if blocks_written >= fsync_last + self._dest_fsync_watermark:
                    fsync_last = blocks_written
                    self.sync()

            try:
                self._f_dest.write(buf)
            except IOError as err:
                raise Error("error while writing blocks %d-%d of '%s': %s"
                            % (start, end, self._dest_path, err))

            self._batch_queue.task_done()
            blocks_written += (end - start + 1)
            bytes_written += len(buf)

            self._update_progress(blocks_written)

        if not self.image_size:
            # The image size was unknown up until now, set it
            self._set_image_size(bytes_written)

        # This is just a sanity check - we should have written exactly
        # 'mapped_cnt' blocks.
        if blocks_written != self.mapped_cnt:
            **raise Error**("wrote %u blocks from image '%s' to '%s', but should "
                        "have %u - bmap file '%s' does not belong to this "
                        "image"
                        % (blocks_written, self._image_path, self._dest_path,
                           self.mapped_cnt, self._bmap_path))

        if self._dest_is_regfile:
            # Make sure the destination file has the same size as the image
            try:
                os.ftruncate(self._f_dest.fileno(), self.image_size)
            except OSError as err:
                raise Error("cannot truncate file '%s': %s"
                            % (self._dest_path, err))

        try:
            self._f_dest.flush()
        except IOError as err:
            raise Error("cannot flush '%s': %s" % (self._dest_path, err))

        if sync:
            self.sync()
……
[root@centos8 bmap-tools]# vim tests/test_bmap_helpers.py +105
    def test_is_zfs_configuration_compatible_unreadable_file(self, mock_open):
        """Check error raised if any IO errors when checking zfs config file"""

        mock_open.side_effect = IOError
        with self.assertRaises(BmapHelpers.Error):
            BmapHelpers.is_zfs_configuration_compatible()
```
Which of the following source code problems can help you to resolve?

**Comment by dedekind** [comment] 2021-03-10 13:50
Hi, I did not fix the error yet, cannot reproduce it on non-ZFS, and I do not have ZFS. But I addressed those many unrelated warnings. I'll try to dig into the error a bit later. Just FYI.

https://github.com/intel/bmap-tools/pull/82

**Comment by dedekind** [comment] 2021-03-11 10:04
Should be fixed in master branch now, please check.

**Comment by dedekind** [comment] 2021-03-11 10:05
I'll close it, you can reopen If it is not really fixed, I assume. Thanks!

**Closed by dedekind** 2021-03-11 10:05 UTC

**Comment by Tom-python0121** [comment] 2021-03-11 10:08
@dedekind Thank you for your help. When will this version be released?

**Comment by dedekind** [comment] 2021-03-11 10:12
Hi, yeah, this would be good idea, I guess v3.6.1 ? Or v3.7? Not sure. Please, give it a test first and confirm the issues are fixed. And let's wait a bit. I'll appreciate if you ping me later again to release the fixes. Thanks!
